name = "discord-bot"
type = "webpack"
route = ''  # Add your route here
zone_id = "${CF_ZONE_ID}"  # Add your zone ID here
 
compatibility_flags = []
workers_dev = true
compatibility_date = "2025-02-27"

# Use environment variables for sensitive information
account_id = "${CF_ACCOUNT_ID}"

# Specify the entry-point of your application
main = "src/index.js"  # Update this path to your actual entry-point file
